const cardData = [
 
  
  


 
 
  
  {
  id: 12,
  url: "images/todolist.png",
  name: "Todo List",
  tech: ["HTML", "CSS", "JavaScript"],
  link: "https://venkateshtodolist.netlify.app/",
  type: "frontend",
  sourcecode1: "https://github.com/Venkatesh7981/todolist",
  sourcecode2: "",
  description: {
    des: "A clean and responsive To-Do List web app that helps users organize their daily tasks effortlessly.",
    features:
      "Key features include adding and deleting todo items with state persisted using the browser's localStorage. Optimized for speed and usability with a lightweight interface."
  }
},
{
  id: 10,
  url: "images/Newsimage.png", // Make sure you have this image in your assets
  name: "NewsApp",
  tech: ["React", "JavaScript", "News API", "Bootstrap"],
  link: "https://venkateshnewsapp.netlify.app/", // Replace with your actual deployed link if different
  type: "frontend",
  sourcecode1: "https://github.com/Venkatesh7981/NewsApp",
  sourcecode2: "",
  description: {
    des: "A dynamic news portal built with React that fetches the latest headlines from an external News API.",
    features:
      "Users can browse top headlines, filter by category, and view news in a clean card-based layout. Built for fast performance and readability."
  }
},


  

  
 {
  id: 11,
  url: "./images/rockpaperscissor.png", 
  name: "Rock Paper Scissor",
  tech: ["HTML", "CSS", "JavaScript"],
  link: "https://venkateshgame.netlify.app/",
  type: "frontend",
  sourcecode1: "https://github.com/Venkatesh7981/Rock_Paper_Scissor",
  sourcecode2: "",
  description: {
    des: "A fun and interactive Rock Paper Scissors game built using JavaScript DOM manipulation.",
    features: "Players can play against the computer with visual feedback, score tracking, and responsive design. Inputs are accepted via button clicks or UI interaction."
  }
},

  
  
  
  {
    id: 5,
    url: "images/drumstick.png",
    name: "Drum player",
    tech: ["HTML", "CSS", "Javascript"],
    link: "https://venkateshdrumkit.netlify.app/",
    type: "frontend",
    sourcecode1: "https://github.com/Venkatesh7981/drumkit",
    sourcecode2: "",
    description: {
      des: "It is instrumental based website which we can use to play different musical instruments",
      features:
        "some of the musical instruments are available which can be played by clicking on it or using key board keys.",
    },
  },
  {
  id: 14,
  url: "images/weather.png",
  name: "Weather App",
  tech: ["HTML", "CSS", "JavaScript", "OpenWeatherMap API", "Bootstrap"],
  link: "https://venkatesh-weatherapp.netlify.app/", // Replace with actual deployment if different
  type: "frontend",
  sourcecode1: "https://github.com/Venkatesh7981/WeatherApp",
  sourcecode2: "",
  description: {
    des: "A responsive weather forecast app that allows users to search by city name and view real-time weather conditions using geolocation and OpenWeatherMap API.",
    features:
      "Displays city-specific weather information including temperature, icon-based condition visuals, and description. Handles invalid cities gracefully. Utilizes async/await and dynamic DOM updates."
  },
},
{
  id: 15,
  url: "images/image_generator.png", // Replace with the actual image name you save for the project
  name: "Image Generator",
  tech: ["MongoDB", "Express.js", "React.js", "Node.js", "OpenAI API", "Tailwind CSS"],
  link: "", // No live site
  type: "fullstack",
  sourcecode1: "https://github.com/Venkatesh7981/MERN_PROJECT",
  sourcecode2: "",
  description: {
    des: "A full-stack AI-powered image generation web app built with the MERN stack. Users can enter text prompts to generate images using the Stability AI API and explore images generated by others through community posts",
    features:
      "Includes prompt-based image generation, secure backend with MongoDB, image storage, and viewing other generated images. Uses RESTful API structure and protected routes. Fully responsive with Tailwind CSS."
  }
}


  
  
 
];

export default cardData;
